spring:
  application:
    name: coroutines_examples

# application configs
application:
  ports:
    output:
      geo:
        adapter: ${OUTPUT_PORT_SELECTED_GEO} #options [nominatim, fallback]
      news:
        adapter: ${OUTPUT_PORT_SELECTED_NEWS} #options [newsdataio, fallback]
      weather:
        adapter: ${OUTPUT_PORT_SELECTED_WEATHER} #options [openweather, fallback]

# external endpoints configs
external:
  news:
    newsdataio:
      url: https://newsdata.io/api/1/news
      token: ${NEWSDATAIO_TOKEN}
      size: 10
  geo:
    nominatim:
      url: https://nominatim.openstreetmap.org/
  weather:
    openweather:
      url: https://api.openweathermap.org/data/2.5/weather
      token: ${WEATHER_TOKEN}

# circuit breaker - resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        failureRateThreshold: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallRateThreshold: 10
        slowCallDurationThreshold: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        registerHealthIndicator: true

# actuator configs
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  health:
    circuitbreakers:
      enabled: true
      ratelimiters: true